-- ZevDash_Custom_Config.lua
-- Edit this file to customize your Sunder Dashboard settings.
-- This will override ZevDash_Default_Config.lua.

-- Example of overriding styles:
-- ZevDash = ZevDash or {}
-- ZevDash.Styles = ZevDash.Styles or {}
-- ZevDash.Styles.textColor = "GoldenRod"
-- ZevDash.Styles.buttonStyle = [[
--     border-width: 2px;
--     border-style: solid;
--     border-color: Gold;
--     background-color: #222222;
--     border-radius: 5px;
-- ]]
